Updated condition for failing if any other env is given[skip ci]

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -51,8 +51,9 @@ jobs:
                   "<< parameters.env >>" != "prod" && 
                   "<< parameters.env >>" != "pre-prod" && 
                   "<< parameters.env >>" != "stage" ]]; then
-              export env="dev"
-              echo "Invalid environment, defaulting to 'dev'"
+              exit 1
+              # export env="dev"
+              # echo "Invalid environment, defaulting to 'dev'"
             else
               export env="<< parameters.env >>"
             fi
